#!/usr/bin/env bash
# Builds the extension and runs the GDScript integration tests headlessly.
#
# Godot only auto-loads extensions that are listed in .godot/extension_list.cfg,
# which is normally generated by opening the project in the editor. To keep this
# script usable without running the editor, the list is created when missing.
#
# Environment:
#   GODOT           path to the Godot binary (default: "godot")
#   FFMPEG_PREFIX   link against a vendored FFmpeg build instead of pkg-config
set -uo pipefail

cd "$(dirname "$0")/.."

GODOT="${GODOT:-godot}"
FFMPEG_PREFIX="${FFMPEG_PREFIX:-}"

echo "== building =="
if [ -n "$FFMPEG_PREFIX" ]; then
	scons -j"$(nproc)" ffmpeg_prefix="$FFMPEG_PREFIX" || exit 1
else
	scons -j"$(nproc)" || exit 1
fi

if [ ! -f project/.godot/extension_list.cfg ]; then
	mkdir -p project/.godot
	echo "res://addons/gdffmpeg/gdffmpeg.gdextension" >project/.godot/extension_list.cfg
	echo "== created project/.godot/extension_list.cfg =="
fi

echo "== running tests =="
timeout 300 "$GODOT" --headless --path project --fixed-fps 60 res://tests/test_runner.tscn
exit $?
